### ISSUE TITLE
Early Feedback / RFC for sb-util JavaScript API

### ISSUE THREAD

**Issue by evmiguel** [bocoup/sb-util#4]
This issue marks a Request For Comments on Bocoup's **sb-util** [JavaScript API proposal](https://github.com/bocoup/sb-util#sb-util-proposal-rfc). Please take a look at our proposal for APIs and  leave any feedback, questions, and concerns on this issue, or create a new one.

We are looking forward to working with the community on sb-util and appreciate your comments on this!

**Comment by tangert** [comment]
hey this is awesome! I'm currently interning at LLK and figuring out how to parse the project.json file to be fed into some machine learning models, so I'll add suggestions

**Comment by tangert** [comment]
in particular, I'm trying to do some machine learning on the AST of stacks (block collections in this API spec), so another cool function might be to convert the current block collection into a more formal AST format (with labels like `type`, `value`, and `children` for each node in the tree).

**Comment by evmiguel** [comment]
Hi @tangert! Thank you for your feedback. Love the idea of the AST format, and will keep this in mind during implementation. Any other feedback, do let us know!

**Comment by nomadtechie** [comment]
@tangert if the output and output is language agnostic (strings, json, etc), would you be able to use tiny wrapper python and use sub-processes to run the util via node?

**Comment by tangert** [comment]
@nomadtechie hi not sure if I'm understanding clearly, are  you asking if I could just use a python wrapper for the node modules? (but yes I'm thinking of doing that).

**Comment by nomadtechie** [comment]
@tangert yes - that is exactly what I meant.

**Comment by tangert** [comment]
@nomadtechie cool yeah, im thinking i could just do that too (although im thinking it might be helpful to have some pythonic apis that feel more natural to the language-- but maybe not)
